[leader]
speed = 20.0
starting_health = 100
texture = "Media/Textures/Eagle.png"

[raptor]
attack_rate = 0.2
flight_pattern = [[45.0, 80.0], [-45.0, 160.0], [45.0, 80.0]]
speed = 50.0
starting_health = 40
texture = "Media/Textures/Raptor.png"

[avenger]
attack_rate = 0.5
flight_pattern = [[45.0, 50.0], [0.0, 50.0], [-45.0, 100.0], [0.0, 50.0], [45.0, 50.0]]
speed = 80.0
starting_health = 20
texture = "Media/Textures/Avenger.png"

[bullet]
damage = 10
speed = 300.0

[missile]
damage = 200
speed = 150.0
